name = "Buff Timer (client)"
description = "Mod that shows information on the character's current buffs"
author = "jimmybaxter"
version = "3.1"
api_version = 10
dst_compatible = true
all_clients_require_mod = false
client_only_mod = true
icon_atlas = "modicon.xml"
icon = "modicon.tex"
server_filter_tags = {}
forumthread = ""
configuration_options = {}
