name = "Buff Timer"
description = "Mod that shows information on the character's current buffs. The info is restored between shards and on connection"
author = "jimmybaxter"
version = "1.1"
api_version = 10
dst_compatible = true
all_clients_require_mod = true
client_only_mod = false
icon_atlas = "modicon.xml"
icon = "modicon.tex"
server_filter_tags = {}
forumthread = ""
configuration_options = {}
