require("constants")

local BuffType = {
    SPICE_CHILI = "SPICE_CHILI",
    SPICE_GARLIC = "SPICE_GARLIC",
    SPICE_HONEY = "SPICE_HONEY",
    VOLT_GOAT_JELLY = "VOLT_GOAT_JELLY",
    MUSHY_CAKE = "MUSHY_CAKE",
    FISH_CORDON_BLEU = "FISH_CORDON_BLEU",
    JELLYBEANS = "JELLYBEANS",
    SOOTHING_TEA = "SOOTHING_TEA",
    FIRE_NETTLES = "FIRE_NETTLES",
    TILLWEED_SALVE = "TILLWEED_SALVE",
    COMPOST_WRAP = "COMPOST_WRAP",
    LESSER_GLOW_BERRY = "LESSER_GLOW_BERRY",
    GLOW_BERRY = "GLOW_BERRY",
    GLOW_BERRY_MOUSSE = "GLOW_BERRY_MOUSSE",
    DRAGON_CHILI_SALAD = "DRAGON_CHILI_SALAD",
    ASPARAGAZPACHO = "ASPARAGAZPACHO",
    ELIXIR_REVENANT_RESTORATIVE = "ELIXIR_REVENANT_RESTORATIVE",
    ELIXIR_SPECTRAL_CURE_ALL = "ELIXIR_SPECTRAL_CURE_ALL",
    ELIXIR_UNYIELDING_DRAUGHT = "ELIXIR_UNYIELDING_DRAUGHT",
    ELIXIR_DISTILLED_VENGEANCE = "ELIXIR_DISTILLED_VENGEANCE",
    ELIXIR_NIGHTSHADE_NOSTRUM = "ELIXIR_NIGHTSHADE_NOSTRUM",
    ELIXIR_VIGOR_MORTIS = "ELIXIR_VIGOR_MORTIS",
    POTION_PHOBIC_EXPERIMENT_SMALL = "POTION_PHOBIC_EXPERIMENT_SMALL",
    POTION_PHOBIC_EXPERIMENT_LARGE = "POTION_PHOBIC_EXPERIMENT_LARGE",
    POTION_SANGUINE_EXPERIMENT_SMALL = "POTION_SANGUINE_EXPERIMENT_SMALL",
    POTION_SANGUINE_EXPERIMENT_LARGE = "POTION_SANGUINE_EXPERIMENT_LARGE",
    POTION_PSYCHOSIS_EXPERIMENT_SMALL = "POTION_PSYCHOSIS_EXPERIMENT_SMALL",
    POTION_PSYCHOSIS_EXPERIMENT_LARGE = "POTION_PSYCHOSIS_EXPERIMENT_LARGE",
    BURNING_FRENZY = "BURNING_FRENZY",
    -- TODO: acid healing salve
}

local BuffImagePrefab = {
    SPICE_CHILI = "spice_chili",
    SPICE_GARLIC = "spice_garlic",
    SPICE_HONEY = "spice_sugar",
    VOLT_GOAT_JELLY = "voltgoatjelly",
    MUSHY_CAKE = "shroomcake",
    FISH_CORDON_BLEU = "frogfishbowl",
    JELLYBEANS = "jellybean",
    SOOTHING_TEA = "sweettea",
    FIRE_NETTLES = "firenettles",
    TILLWEED_SALVE = "tillweedsalve",
    COMPOST_WRAP = "compostwrap",
    LESSER_GLOW_BERRY = "wormlight_lesser",
    GLOW_BERRY = "wormlight",
    GLOW_BERRY_MOUSSE = "glowberrymousse",
    DRAGON_CHILI_SALAD = "dragonchilisalad",
    ASPARAGAZPACHO = "gazpacho",
    ELIXIR_REVENANT_RESTORATIVE = "ghostlyelixir_slowregen",
    ELIXIR_SPECTRAL_CURE_ALL = "ghostlyelixir_fastregen",
    ELIXIR_UNYIELDING_DRAUGHT = "ghostlyelixir_shield",
    ELIXIR_DISTILLED_VENGEANCE = "ghostlyelixir_retaliation",
    ELIXIR_NIGHTSHADE_NOSTRUM = "ghostlyelixir_attack",
    ELIXIR_VIGOR_MORTIS = "ghostlyelixir_speed",
    POTION_PHOBIC_EXPERIMENT_SMALL = "halloweenpotion_bravery_small",
    POTION_PHOBIC_EXPERIMENT_LARGE = "halloweenpotion_bravery_large",
    POTION_SANGUINE_EXPERIMENT_SMALL = "halloweenpotion_health_small",
    POTION_SANGUINE_EXPERIMENT_LARGE = "halloweenpotion_health_large",
    POTION_PSYCHOSIS_EXPERIMENT_SMALL = "halloweenpotion_sanity_small",
    POTION_PSYCHOSIS_EXPERIMENT_LARGE = "halloweenpotion_sanity_large",
    BURNING_FRENZY = "torch",
}

local BuffTimerName = {
    SPICE_CHILI = "buffover",
    SPICE_GARLIC = "buffover",
    SPICE_HONEY = "buffover",
    VOLT_GOAT_JELLY = "buffover",
    MUSHY_CAKE = "buffover",
    FISH_CORDON_BLEU = "buffover",
    JELLYBEANS = "regenover",
    SOOTHING_TEA = "regenover",
    TILLWEED_SALVE = "regenover",
    COMPOST_WRAP = "regenover",
    ELIXIR_REVENANT_RESTORATIVE = "decay",
    ELIXIR_SPECTRAL_CURE_ALL = "decay",
    ELIXIR_UNYIELDING_DRAUGHT = "decay",
    ELIXIR_DISTILLED_VENGEANCE = "decay",
    ELIXIR_NIGHTSHADE_NOSTRUM = "decay",
    ELIXIR_VIGOR_MORTIS = "decay",
    POTION_PHOBIC_EXPERIMENT_SMALL = "regenover",
    POTION_PHOBIC_EXPERIMENT_LARGE = "regenover",
    POTION_SANGUINE_EXPERIMENT_SMALL = "regenover",
    POTION_SANGUINE_EXPERIMENT_LARGE = "regenover",
    POTION_PSYCHOSIS_EXPERIMENT_SMALL = "regenover",
    POTION_PSYCHOSIS_EXPERIMENT_LARGE = "regenover",
}

local BuffByPrefab = {
    buff_attack = BuffType.SPICE_CHILI,
    buff_playerabsorption = BuffType.SPICE_GARLIC,
    buff_workeffectiveness = BuffType.SPICE_HONEY,
    buff_electricattack = BuffType.VOLT_GOAT_JELLY,
    buff_sleepresistance = BuffType.MUSHY_CAKE,
    buff_moistureimmunity = BuffType.FISH_CORDON_BLEU,
    healthregenbuff = BuffType.JELLYBEANS,
    sweettea_buff = BuffType.SOOTHING_TEA,
    firenettle_toxin = BuffType.FIRE_NETTLES,
    tillweedsalve_buff = BuffType.TILLWEED_SALVE,
    compostheal_buff = BuffType.COMPOST_WRAP,
    wormlight_light_lesser = BuffType.LESSER_GLOW_BERRY,
    wormlight_light = BuffType.GLOW_BERRY,
    wormlight_light_greater = BuffType.GLOW_BERRY_MOUSSE,
    ghostlyelixir_slowregen_buff = BuffType.ELIXIR_REVENANT_RESTORATIVE,
    ghostlyelixir_fastregen_buff = BuffType.ELIXIR_SPECTRAL_CURE_ALL,
    ghostlyelixir_shield_buff = BuffType.ELIXIR_UNYIELDING_DRAUGHT,
    ghostlyelixir_retaliation_buff = BuffType.ELIXIR_DISTILLED_VENGEANCE,
    ghostlyelixir_attack_buff = BuffType.ELIXIR_NIGHTSHADE_NOSTRUM,
    ghostlyelixir_speed_buff = BuffType.ELIXIR_VIGOR_MORTIS,
    halloweenpotion_bravery_small_buff = BuffType.POTION_PHOBIC_EXPERIMENT_SMALL,
    halloweenpotion_bravery_large_buff = BuffType.POTION_PHOBIC_EXPERIMENT_LARGE,
    halloweenpotion_health_small_buff = BuffType.POTION_SANGUINE_EXPERIMENT_SMALL,
    halloweenpotion_health_large_buff = BuffType.POTION_SANGUINE_EXPERIMENT_LARGE,
    halloweenpotion_sanity_small_buff = BuffType.POTION_PSYCHOSIS_EXPERIMENT_SMALL,
    halloweenpotion_sanity_large_buff = BuffType.POTION_PSYCHOSIS_EXPERIMENT_LARGE,
    buff_firefrenzy = BuffType.BURNING_FRENZY,
}

return {
    BuffType = BuffType,
    BuffImagePrefab = BuffImagePrefab,
    BuffTimerName = BuffTimerName,
    BuffByPrefab = BuffByPrefab,
}
