require("constants")
require("strings")
require("tuning")

local BuffType = {
    SPICE_CHILI = "SPICE_CHILI",
    SPICE_GARLIC = "SPICE_GARLIC",
    SPICE_HONEY = "SPICE_HONEY",
    VOLT_GOAT_JELLY = "VOLT_GOAT_JELLY",
    MUSHY_CAKE = "MUSHY_CAKE",
    FISH_CORDON_BLEU = "FISH_CORDON_BLEU",
    JELLYBEANS = "JELLYBEANS",
    SOOTHING_TEA = "SOOTHING_TEA",
    FIRE_NETTLES = "FIRE_NETTLES",
    TILLWEED_SALVE = "TILLWEED_SALVE",
    COMPOST_WRAP = "COMPOST_WRAP",
    LESSER_GLOW_BERRY = "LESSER_GLOW_BERRY",
    GLOW_BERRY = "GLOW_BERRY",
    GLOW_BERRY_MOUSSE = "GLOW_BERRY_MOUSSE",
    DRAGON_CHILI_SALAD = "DRAGON_CHILI_SALAD",
    ASPARAGAZPACHO = "ASPARAGAZPACHO",
    ELIXIR_REVENANT_RESTORATIVE = "ELIXIR_REVENANT_RESTORATIVE",
    ELIXIR_SPECTRAL_CURE_ALL = "ELIXIR_SPECTRAL_CURE_ALL",
    ELIXIR_UNYIELDING_DRAUGHT = "ELIXIR_UNYIELDING_DRAUGHT",
    ELIXIR_DISTILLED_VENGEANCE = "ELIXIR_DISTILLED_VENGEANCE",
    ELIXIR_NIGHTSHADE_NOSTRUM = "ELIXIR_NIGHTSHADE_NOSTRUM",
    ELIXIR_VIGOR_MORTIS = "ELIXIR_VIGOR_MORTIS",
    POTION_PHOBIC_EXPERIMENT_SMALL = "POTION_PHOBIC_EXPERIMENT_SMALL",
    POTION_PHOBIC_EXPERIMENT_LARGE = "POTION_PHOBIC_EXPERIMENT_LARGE",
    POTION_SANGUINE_EXPERIMENT_SMALL = "POTION_SANGUINE_EXPERIMENT_SMALL",
    POTION_SANGUINE_EXPERIMENT_LARGE = "POTION_SANGUINE_EXPERIMENT_LARGE",
    POTION_PSYCHOSIS_EXPERIMENT_SMALL = "POTION_PSYCHOSIS_EXPERIMENT_SMALL",
    POTION_PSYCHOSIS_EXPERIMENT_LARGE = "POTION_PSYCHOSIS_EXPERIMENT_LARGE",
    BURNING_FRENZY = "BURNING_FRENZY",
    -- TODO: acid healing salve
}

local BuffDuration = {
    SPICE_CHILI = TUNING.BUFF_ATTACK_DURATION,
    SPICE_GARLIC = TUNING.BUFF_PLAYERABSORPTION_DURATION,
    SPICE_HONEY = TUNING.BUFF_WORKEFFECTIVENESS_DURATION,
    VOLT_GOAT_JELLY = TUNING.BUFF_ELECTRICATTACK_DURATION,
    MUSHY_CAKE = TUNING.SLEEPRESISTBUFF_TIME,
    FISH_CORDON_BLEU = TUNING.BUFF_MOISTUREIMMUNITY_DURATION,
    JELLYBEANS = TUNING.JELLYBEAN_DURATION,
    SOOTHING_TEA = TUNING.SWEETTEA_DURATION,
    FIRE_NETTLES = TUNING.FIRE_NETTLE_TOXIN_DURATION,
    TILLWEED_SALVE = TUNING.TILLWEEDSALVE_DURATION,
    COMPOST_WRAP = (
        TUNING.WORMWOOD_COMPOST_HEAL_VALUES[math.ceil(TUNING.COMPOSTWRAP_NUTRIENTS[TUNING.COMPOST_NUTRIENTS_INDEX] / 8)]
        or TUNING.WORMWOOD_COMPOST_HEAL_VALUES[1]
    ) * (TUNING.WORMWOOD_COMPOST_HEALOVERTIME_TICK / TUNING.WORMWOOD_COMPOST_HEALOVERTIME_HEALTH),
    LESSER_GLOW_BERRY = TUNING.WORMLIGHT_DURATION * 0.25,
    GLOW_BERRY = TUNING.WORMLIGHT_DURATION,
    GLOW_BERRY_MOUSSE = TUNING.WORMLIGHT_DURATION * 4,
    DRAGON_CHILI_SALAD = TUNING.BUFF_FOOD_TEMP_DURATION,
    ASPARAGAZPACHO = TUNING.BUFF_FOOD_TEMP_DURATION,
    ELIXIR_REVENANT_RESTORATIVE = TUNING.GHOSTLYELIXIR_SLOWREGEN_DURATION,
    ELIXIR_SPECTRAL_CURE_ALL = TUNING.GHOSTLYELIXIR_FASTREGEN_DURATION,
    ELIXIR_UNYIELDING_DRAUGHT = TUNING.GHOSTLYELIXIR_SHIELD_DURATION,
    ELIXIR_DISTILLED_VENGEANCE = TUNING.GHOSTLYELIXIR_RETALIATION_DURATION,
    ELIXIR_NIGHTSHADE_NOSTRUM = TUNING.GHOSTLYELIXIR_DAMAGE_DURATION,
    ELIXIR_VIGOR_MORTIS = TUNING.GHOSTLYELIXIR_SPEED_DURATION,
    POTION_PHOBIC_EXPERIMENT_SMALL = TUNING.TOTAL_DAY_TIME * 0.5,
    POTION_PHOBIC_EXPERIMENT_LARGE = TUNING.TOTAL_DAY_TIME * 0.75,
    POTION_SANGUINE_EXPERIMENT_SMALL = TUNING.SEG_TIME * 2,
    POTION_SANGUINE_EXPERIMENT_LARGE = TUNING.SEG_TIME * 2,
    POTION_PSYCHOSIS_EXPERIMENT_SMALL = TUNING.SEG_TIME * 2,
    POTION_PSYCHOSIS_EXPERIMENT_LARGE = TUNING.SEG_TIME * 2,
    BURNING_FRENZY = TUNING.WILLOW_FIREFRENZY_DURATION,
}

local BuffImagePrefab = {
    SPICE_CHILI = "spice_chili",
    SPICE_GARLIC = "spice_garlic",
    SPICE_HONEY = "spice_sugar",
    VOLT_GOAT_JELLY = "voltgoatjelly",
    MUSHY_CAKE = "shroomcake",
    FISH_CORDON_BLEU = "frogfishbowl",
    JELLYBEANS = "jellybean",
    SOOTHING_TEA = "sweettea",
    FIRE_NETTLES = "firenettles",
    TILLWEED_SALVE = "tillweedsalve",
    COMPOST_WRAP = "compostwrap",
    LESSER_GLOW_BERRY = "wormlight_lesser",
    GLOW_BERRY = "wormlight",
    GLOW_BERRY_MOUSSE = "glowberrymousse",
    DRAGON_CHILI_SALAD = "dragonchilisalad",
    ASPARAGAZPACHO = "gazpacho",
    ELIXIR_REVENANT_RESTORATIVE = "ghostlyelixir_slowregen",
    ELIXIR_SPECTRAL_CURE_ALL = "ghostlyelixir_fastregen",
    ELIXIR_UNYIELDING_DRAUGHT = "ghostlyelixir_shield",
    ELIXIR_DISTILLED_VENGEANCE = "ghostlyelixir_retaliation",
    ELIXIR_NIGHTSHADE_NOSTRUM = "ghostlyelixir_attack",
    ELIXIR_VIGOR_MORTIS = "ghostlyelixir_speed",
    POTION_PHOBIC_EXPERIMENT_SMALL = "halloweenpotion_bravery_small",
    POTION_PHOBIC_EXPERIMENT_LARGE = "halloweenpotion_bravery_large",
    POTION_SANGUINE_EXPERIMENT_SMALL = "halloweenpotion_health_small",
    POTION_SANGUINE_EXPERIMENT_LARGE = "halloweenpotion_health_large",
    POTION_PSYCHOSIS_EXPERIMENT_SMALL = "halloweenpotion_sanity_small",
    POTION_PSYCHOSIS_EXPERIMENT_LARGE = "halloweenpotion_sanity_large",
    BURNING_FRENZY = "torch",
}

local BuffByFoodPrefab = {
    voltgoatjelly = BuffType.VOLT_GOAT_JELLY,
    shroomcake = BuffType.MUSHY_CAKE,
    frogfishbowl = BuffType.FISH_CORDON_BLEU,
    jellybean = BuffType.JELLYBEANS,
    sweettea = BuffType.SOOTHING_TEA,
    firenettles = BuffType.FIRE_NETTLES,
    wormlight_lesser = BuffType.LESSER_GLOW_BERRY,
    wormlight = BuffType.GLOW_BERRY,
    glowberrymousse = BuffType.GLOW_BERRY_MOUSSE,
    dragonchilisalad = BuffType.DRAGON_CHILI_SALAD,
    gazpacho = BuffType.ASPARAGAZPACHO,
    halloweenpotion_bravery_small = BuffType.POTION_PHOBIC_EXPERIMENT_SMALL,
    halloweenpotion_bravery_large = BuffType.POTION_PHOBIC_EXPERIMENT_LARGE,
    halloweenpotion_health_small = BuffType.POTION_SANGUINE_EXPERIMENT_SMALL,
    halloweenpotion_health_large = BuffType.POTION_SANGUINE_EXPERIMENT_LARGE,
    halloweenpotion_sanity_small = BuffType.POTION_PSYCHOSIS_EXPERIMENT_SMALL,
    halloweenpotion_sanity_large = BuffType.POTION_PSYCHOSIS_EXPERIMENT_LARGE,
}

local BuffByHealingPrefab = {
    tillweedsalve = BuffType.TILLWEED_SALVE,
    compostwrap = BuffType.COMPOST_WRAP,
}

local BuffBySpicePrefab = {
    spice_chili = BuffType.SPICE_CHILI,
    spice_garlic = BuffType.SPICE_GARLIC,
    spice_sugar = BuffType.SPICE_HONEY,
}

local BuffByElixirPrefab = {
    ghostlyelixir_slowregen = BuffType.ELIXIR_REVENANT_RESTORATIVE,
    ghostlyelixir_fastregen = BuffType.ELIXIR_SPECTRAL_CURE_ALL,
    ghostlyelixir_shield = BuffType.ELIXIR_UNYIELDING_DRAUGHT,
    ghostlyelixir_retaliation = BuffType.ELIXIR_DISTILLED_VENGEANCE,
    ghostlyelixir_attack = BuffType.ELIXIR_NIGHTSHADE_NOSTRUM,
    ghostlyelixir_speed = BuffType.ELIXIR_VIGOR_MORTIS,
}

local BuffBySpellPrefab = {
    [STRINGS.PYROMANCY.FIRE_FRENZY] = BuffType.BURNING_FRENZY,
}

local OverlappingBuffedFoods = {
    {BuffType.LESSER_GLOW_BERRY, BuffType.GLOW_BERRY, BuffType.GLOW_BERRY_MOUSSE},
    {BuffType.DRAGON_CHILI_SALAD, BuffType.ASPARAGAZPACHO},
    {
        BuffType.ELIXIR_REVENANT_RESTORATIVE,
        BuffType.ELIXIR_SPECTRAL_CURE_ALL,
        BuffType.ELIXIR_UNYIELDING_DRAUGHT,
        BuffType.ELIXIR_DISTILLED_VENGEANCE,
        BuffType.ELIXIR_NIGHTSHADE_NOSTRUM,
        BuffType.ELIXIR_VIGOR_MORTIS,
    },
    {BuffType.POTION_PHOBIC_EXPERIMENT_SMALL, BuffType.POTION_PHOBIC_EXPERIMENT_LARGE},
    {BuffType.POTION_SANGUINE_EXPERIMENT_SMALL, BuffType.POTION_SANGUINE_EXPERIMENT_LARGE},
    {BuffType.POTION_PSYCHOSIS_EXPERIMENT_SMALL, BuffType.POTION_PSYCHOSIS_EXPERIMENT_LARGE},
}

return {
    BuffType = BuffType,
    BuffDuration = BuffDuration,
    BuffImagePrefab = BuffImagePrefab,
    BuffByFoodPrefab = BuffByFoodPrefab,
    BuffByHealingPrefab = BuffByHealingPrefab,
    BuffBySpicePrefab = BuffBySpicePrefab,
    BuffByElixirPrefab = BuffByElixirPrefab,
    BuffBySpellPrefab = BuffBySpellPrefab,
    OverlappingBuffedFoods = OverlappingBuffedFoods,
}
